# Generated by scripts/build-cli-binaries.sh — do not hand-edit.
# Copy to getdebug-ai/homebrew-tap Formula/getdebug.rb on each release.
class Getdebug < Formula
  desc "AI-powered codebase analyzer and auto-fixer — security + bug checks before you ship"
  homepage "https://getdebug.dev"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/getdebug-ai/cli/releases/download/v0.4.0/getdebug_0.4.0_darwin_arm64.tar.gz"
      sha256 "ee4794c51361ee5a915d1e0309eb3377802161aded4ea409be3d46446f27ced8"
    end
    on_intel do
      url "https://github.com/getdebug-ai/cli/releases/download/v0.4.0/getdebug_0.4.0_darwin_x86_64.tar.gz"
      sha256 "489029c71749a617db6b0c5127007269ba6abfd2552eb017edaacd2ce9ee1276"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/getdebug-ai/cli/releases/download/v0.4.0/getdebug_0.4.0_linux_arm64.tar.gz"
      sha256 "a10f3b4ed7d45a33966034d93c26382d4a5af97a158f00a42ef63fe82923f6ce"
    end
    on_intel do
      url "https://github.com/getdebug-ai/cli/releases/download/v0.4.0/getdebug_0.4.0_linux_x86_64.tar.gz"
      sha256 "ba3c842af3c7852c0b406a026e6c2323543c5cad179cad4091a5d5486874163a"
    end
  end

  def install
    bin.install "getdebug"
  end

  test do
    assert_match "getdebug version #{version}", shell_output("#{bin}/getdebug --version")
  end
end
