# Generated by scripts/build-cli-binaries.sh — do not hand-edit.
# Copy to getdebug-ai/homebrew-tap Formula/getdebug.rb on each release.
class Getdebug < Formula
  desc "AI-powered codebase analyzer and auto-fixer — security + bug checks before you ship"
  homepage "https://getdebug.dev"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/getdebug-ai/cli/releases/download/v0.3.0/getdebug_0.3.0_darwin_arm64.tar.gz"
      sha256 "3dbc5cbeb6ac30091b34e9c30813eab7c8fa77421546bf8818fcbd4445f049fe"
    end
    on_intel do
      url "https://github.com/getdebug-ai/cli/releases/download/v0.3.0/getdebug_0.3.0_darwin_x86_64.tar.gz"
      sha256 "c30d15ca1507e639f37126d0f5e7638f03a9e5e384f6b7c80f2f17b57543c4a3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/getdebug-ai/cli/releases/download/v0.3.0/getdebug_0.3.0_linux_arm64.tar.gz"
      sha256 "d642fac6bdbc9d92b9a2bf02679be1b92e654b11c8196f3171f14f36fa314ec7"
    end
    on_intel do
      url "https://github.com/getdebug-ai/cli/releases/download/v0.3.0/getdebug_0.3.0_linux_x86_64.tar.gz"
      sha256 "808eab21f783fc75d4b29aee9788267b160412573ee46fbf1d06b07317a8f78d"
    end
  end

  def install
    bin.install "getdebug"
  end

  test do
    assert_match "getdebug version #{version}", shell_output("#{bin}/getdebug --version")
  end
end
